/**
 * Curated Phosphor glyphs available in the IconPicker's "Icon" tab. Hand-
 * picked for "labels things in a knowledge-management app" — workflow,
 * people, time, files, status, places, communication. Add more as use
 * cases warrant; mass-importing the full Phosphor catalog would blow up
 * the renderer bundle.
 *
 * Each entry: `{ name: <glyph-id-in-pack>, keywords: <search terms>, comp: <Phosphor React component> }`.
 * `name` is the pack-local id used in `Icon.value` as `"phosphor/<name>"`.
 *
 * When user-pickable icon packs land (task #14), this becomes one of many
 * registered packs; the picker UI iterates the active pack's entries.
 */

import {
	Airplane,
	Alarm,
	Archive,
	ArrowSquareOut,
	Atom,
	Backpack,
	Barbell,
	Bell,
	Bicycle,
	Book,
	BookOpen,
	Bookmark,
	Bookmarks,
	Brain,
	Briefcase,
	Bug,
	Building,
	Calculator,
	Calendar,
	Camera,
	Car,
	ChartBar,
	ChartLine,
	ChartPie,
	ChatCircle,
	CheckCircle,
	Clipboard,
	Clock,
	Cloud,
	Code,
	Coffee,
	Compass,
	Cookie,
	CreditCard,
	Cube,
	Database,
	Desktop,
	Diamond,
	Drop,
	Envelope,
	Eye,
	FileText,
	Files,
	FilmStrip,
	Fingerprint,
	Fire,
	Flag,
	FlowerLotus,
	Folder,
	FolderSimple,
	Gear,
	Gift,
	Globe,
	GraduationCap,
	Hammer,
	HandHeart,
	Hash,
	Headphones,
	Heart,
	Heartbeat,
	House,
	IdentificationBadge,
	Image,
	Info,
	Key,
	Laptop,
	Lightbulb,
	Link,
	LinkSimple,
	List,
	ListChecks,
	Lock,
	MagicWand,
	MagnifyingGlass,
	MapPin,
	MapTrifold,
	Megaphone,
	Microphone,
	MoneyWavy,
	Moon,
	MusicNote,
	Newspaper,
	Note,
	NotePencil,
	Package,
	Paperclip,
	Path,
	Pen,
	Pencil,
	Person,
	Phone,
	type Icon as PhosphorIcon,
	PhosphorLogo,
	Pizza,
	Plant,
	Plus,
	Pulse,
	PushPin,
	PuzzlePiece,
	Question,
	Rocket,
	Scales,
	Scissors,
	Shield,
	ShoppingBag,
	ShoppingCart,
	Smiley,
	SpeakerHigh,
	Star,
	Sun,
	Sword,
	Tag,
	Target,
	Television,
	Tent,
	Terminal,
	ThumbsUp,
	Ticket,
	Tree,
	Trophy,
	Umbrella,
	User,
	Users,
	Video,
	Wallet,
	Warning,
	WaveSine,
	Wrench,
} from "@phosphor-icons/react";

export const PHOSPHOR_PACK_ID = "phosphor" as const;

export type PackGlyph = {
	name: string;
	keywords: string;
	comp: PhosphorIcon;
};

export const PHOSPHOR_GLYPHS: readonly PackGlyph[] = [
	{ name: "airplane", keywords: "airplane plane travel flight", comp: Airplane },
	{ name: "alarm", keywords: "alarm clock time wake", comp: Alarm },
	{ name: "archive", keywords: "archive box storage", comp: Archive },
	{ name: "arrow-out", keywords: "arrow external link out open", comp: ArrowSquareOut },
	{ name: "atom", keywords: "atom science physics", comp: Atom },
	{ name: "backpack", keywords: "backpack school bag", comp: Backpack },
	{ name: "barbell", keywords: "barbell gym fitness weight", comp: Barbell },
	{ name: "bell", keywords: "bell notification alert", comp: Bell },
	{ name: "bicycle", keywords: "bicycle bike cycle", comp: Bicycle },
	{ name: "book", keywords: "book read library", comp: Book },
	{ name: "book-open", keywords: "book open read study", comp: BookOpen },
	{ name: "bookmark", keywords: "bookmark save", comp: Bookmark },
	{ name: "bookmarks", keywords: "bookmarks saved list", comp: Bookmarks },
	{ name: "brain", keywords: "brain mind think idea", comp: Brain },
	{ name: "briefcase", keywords: "briefcase work job", comp: Briefcase },
	{ name: "bug", keywords: "bug issue defect insect", comp: Bug },
	{ name: "building", keywords: "building office company", comp: Building },
	{ name: "calculator", keywords: "calculator math number", comp: Calculator },
	{ name: "calendar", keywords: "calendar date schedule", comp: Calendar },
	{ name: "camera", keywords: "camera photo picture", comp: Camera },
	{ name: "car", keywords: "car vehicle drive", comp: Car },
	{ name: "chart-bar", keywords: "chart bar graph data", comp: ChartBar },
	{ name: "chart-line", keywords: "chart line graph trend", comp: ChartLine },
	{ name: "chart-pie", keywords: "chart pie percent", comp: ChartPie },
	{ name: "chat", keywords: "chat message bubble", comp: ChatCircle },
	{ name: "check", keywords: "check done complete tick", comp: CheckCircle },
	{ name: "clipboard", keywords: "clipboard copy task", comp: Clipboard },
	{ name: "clock", keywords: "clock time", comp: Clock },
	{ name: "cloud", keywords: "cloud weather sync", comp: Cloud },
	{ name: "code", keywords: "code programming dev", comp: Code },
	{ name: "coffee", keywords: "coffee drink cafe", comp: Coffee },
	{ name: "compass", keywords: "compass direction navigate", comp: Compass },
	{ name: "cookie", keywords: "cookie biscuit", comp: Cookie },
	{ name: "credit-card", keywords: "credit card payment money", comp: CreditCard },
	{ name: "cube", keywords: "cube box object", comp: Cube },
	{ name: "database", keywords: "database storage data", comp: Database },
	{ name: "desktop", keywords: "desktop computer monitor", comp: Desktop },
	{ name: "diamond", keywords: "diamond gem precious", comp: Diamond },
	{ name: "drop", keywords: "drop water liquid", comp: Drop },
	{ name: "envelope", keywords: "envelope mail email", comp: Envelope },
	{ name: "eye", keywords: "eye view watch see", comp: Eye },
	{ name: "file-text", keywords: "file text document", comp: FileText },
	{ name: "files", keywords: "files documents", comp: Files },
	{ name: "film-strip", keywords: "film movie strip cinema", comp: FilmStrip },
	{ name: "fingerprint", keywords: "fingerprint biometric identity", comp: Fingerprint },
	{ name: "fire", keywords: "fire hot trending", comp: Fire },
	{ name: "flag", keywords: "flag mark report", comp: Flag },
	{ name: "flower", keywords: "flower lotus plant zen", comp: FlowerLotus },
	{ name: "folder", keywords: "folder directory", comp: Folder },
	{ name: "folder-simple", keywords: "folder simple", comp: FolderSimple },
	{ name: "gear", keywords: "gear settings cog", comp: Gear },
	{ name: "gift", keywords: "gift present box", comp: Gift },
	{ name: "globe", keywords: "globe world web internet", comp: Globe },
	{ name: "graduation", keywords: "graduation cap school college", comp: GraduationCap },
	{ name: "hammer", keywords: "hammer tool build", comp: Hammer },
	{ name: "hand-heart", keywords: "hand heart care give", comp: HandHeart },
	{ name: "hash", keywords: "hash tag pound", comp: Hash },
	{ name: "headphones", keywords: "headphones audio music", comp: Headphones },
	{ name: "heart", keywords: "heart love favorite", comp: Heart },
	{ name: "heartbeat", keywords: "heartbeat pulse health", comp: Heartbeat },
	{ name: "house", keywords: "house home", comp: House },
	{ name: "id-badge", keywords: "id badge identity card", comp: IdentificationBadge },
	{ name: "image", keywords: "image picture photo", comp: Image },
	{ name: "info", keywords: "info information detail", comp: Info },
	{ name: "key", keywords: "key password security", comp: Key },
	{ name: "laptop", keywords: "laptop computer notebook", comp: Laptop },
	{ name: "lightbulb", keywords: "lightbulb idea bright", comp: Lightbulb },
	{ name: "link", keywords: "link chain url", comp: Link },
	{ name: "link-simple", keywords: "link simple url", comp: LinkSimple },
	{ name: "list", keywords: "list items lines", comp: List },
	{ name: "list-checks", keywords: "list checks todo task", comp: ListChecks },
	{ name: "lock", keywords: "lock secure private", comp: Lock },
	{ name: "magic-wand", keywords: "magic wand spell effects", comp: MagicWand },
	{ name: "magnifying-glass", keywords: "magnifying glass search find", comp: MagnifyingGlass },
	{ name: "map-pin", keywords: "map pin location place", comp: MapPin },
	{ name: "map", keywords: "map fold geography", comp: MapTrifold },
	{ name: "megaphone", keywords: "megaphone announce loud", comp: Megaphone },
	{ name: "microphone", keywords: "microphone record audio voice", comp: Microphone },
	{ name: "money", keywords: "money cash currency dollar", comp: MoneyWavy },
	{ name: "moon", keywords: "moon night dark sleep", comp: Moon },
	{ name: "music", keywords: "music note song", comp: MusicNote },
	{ name: "newspaper", keywords: "newspaper article press news", comp: Newspaper },
	{ name: "note", keywords: "note paper memo", comp: Note },
	{ name: "note-pencil", keywords: "note pencil edit write", comp: NotePencil },
	{ name: "package", keywords: "package box ship delivery", comp: Package },
	{ name: "paperclip", keywords: "paperclip attach file", comp: Paperclip },
	{ name: "path", keywords: "path route line", comp: Path },
	{ name: "pen", keywords: "pen write ink", comp: Pen },
	{ name: "pencil", keywords: "pencil write edit draw", comp: Pencil },
	{ name: "person", keywords: "person human user", comp: Person },
	{ name: "phone", keywords: "phone call mobile", comp: Phone },
	{ name: "phosphor", keywords: "phosphor logo brand", comp: PhosphorLogo },
	{ name: "pizza", keywords: "pizza food slice", comp: Pizza },
	{ name: "plant", keywords: "plant green grow", comp: Plant },
	{ name: "plus", keywords: "plus add new", comp: Plus },
	{ name: "pulse", keywords: "pulse heartbeat health activity", comp: Pulse },
	{ name: "push-pin", keywords: "push pin tack mark sticky", comp: PushPin },
	{ name: "puzzle", keywords: "puzzle piece extension", comp: PuzzlePiece },
	{ name: "question", keywords: "question help mark", comp: Question },
	{ name: "rocket", keywords: "rocket launch fast ship", comp: Rocket },
	{ name: "scales", keywords: "scales balance justice", comp: Scales },
	{ name: "scissors", keywords: "scissors cut split", comp: Scissors },
	{ name: "shield", keywords: "shield protect security", comp: Shield },
	{ name: "shopping-bag", keywords: "shopping bag buy retail", comp: ShoppingBag },
	{ name: "shopping-cart", keywords: "shopping cart buy retail", comp: ShoppingCart },
	{ name: "smiley", keywords: "smiley face happy emoji", comp: Smiley },
	{ name: "speaker-high", keywords: "speaker volume loud audio", comp: SpeakerHigh },
	{ name: "star", keywords: "star favorite rating", comp: Star },
	{ name: "sun", keywords: "sun day light bright", comp: Sun },
	{ name: "sword", keywords: "sword weapon fight", comp: Sword },
	{ name: "tag", keywords: "tag label price", comp: Tag },
	{ name: "target", keywords: "target goal aim", comp: Target },
	{ name: "television", keywords: "television tv screen monitor", comp: Television },
	{ name: "tent", keywords: "tent camp outdoor", comp: Tent },
	{ name: "terminal", keywords: "terminal shell command line", comp: Terminal },
	{ name: "thumbs-up", keywords: "thumbs up like good approve", comp: ThumbsUp },
	{ name: "ticket", keywords: "ticket pass event", comp: Ticket },
	{ name: "tree", keywords: "tree plant nature", comp: Tree },
	{ name: "trophy", keywords: "trophy award win", comp: Trophy },
	{ name: "umbrella", keywords: "umbrella rain weather", comp: Umbrella },
	{ name: "user", keywords: "user person profile", comp: User },
	{ name: "users", keywords: "users people team group", comp: Users },
	{ name: "video", keywords: "video camera recording", comp: Video },
	{ name: "wallet", keywords: "wallet money pay", comp: Wallet },
	{ name: "warning", keywords: "warning alert caution", comp: Warning },
	{ name: "wave", keywords: "wave sine sound signal", comp: WaveSine },
	{ name: "wrench", keywords: "wrench tool fix", comp: Wrench },
];

const GLYPH_BY_NAME: ReadonlyMap<string, PackGlyph> = new Map(
	PHOSPHOR_GLYPHS.map((g) => [g.name, g]),
);

export function resolvePackGlyph(value: string): PackGlyph | null {
	const [pack, name] = value.split("/");
	if (pack !== PHOSPHOR_PACK_ID || !name) return null;
	return GLYPH_BY_NAME.get(name) ?? null;
}

export function searchPhosphor(query: string): readonly PackGlyph[] {
	const q = query.trim().toLowerCase();
	if (!q) return PHOSPHOR_GLYPHS;
	return PHOSPHOR_GLYPHS.filter((g) => g.name.includes(q) || g.keywords.includes(q));
}
